cargo-features = ["edition"]

[package]
name = "dewr"
version = "0.1.0"
authors = ["Markus Ast <m@rkusa.st>"]
edition = "2018"

[lib]
crate-type = ["dylib"]

[dependencies]
lua51 = { path = "../lua51" }
libc = "0.2"
